/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iProofVerificationSol from "./IProofVerification.sol";
export type { iProofVerificationSol };
export type { IBunnyBattle } from "./IBunnyBattle";
