/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IBoardVerifier__factory } from "./IBoardVerifier__factory";
export { IMoveVerifier__factory } from "./IMoveVerifier__factory";
