/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace Battleship {
  export type MoveStruct = { x: BigNumberish; y: BigNumberish; isHit: boolean };

  export type MoveStructOutput = [x: bigint, y: bigint, isHit: boolean] & {
    x: bigint;
    y: bigint;
    isHit: boolean;
  };

  export type GamePublicMetadataStruct = {
    player1: AddressLike;
    player2: AddressLike;
    player1Hash: BigNumberish;
    player2Hash: BigNumberish;
    moves: Battleship.MoveStruct[];
  };

  export type GamePublicMetadataStructOutput = [
    player1: string,
    player2: string,
    player1Hash: bigint,
    player2Hash: bigint,
    moves: Battleship.MoveStructOutput[]
  ] & {
    player1: string;
    player2: string;
    player1Hash: bigint;
    player2Hash: bigint;
    moves: Battleship.MoveStructOutput[];
  };
}

export interface BattleshipInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "accumulatedFee"
      | "claimCommission"
      | "createGame"
      | "createVerifier"
      | "game"
      | "joinGame"
      | "moveVerifier"
      | "owner"
      | "renounceOwnership"
      | "submitMove"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;

  encodeFunctionData(
    functionFragment: "accumulatedFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimCommission",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createGame",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createVerifier",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "game", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "joinGame",
    values: [BigNumberish, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "moveVerifier",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitMove",
    values: [BigNumberish, BigNumberish, BigNumberish, BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "accumulatedFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimCommission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createGame", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "game", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "joinGame", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "moveVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "submitMove", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Battleship extends BaseContract {
  connect(runner?: ContractRunner | null): Battleship;
  waitForDeployment(): Promise<this>;

  interface: BattleshipInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  accumulatedFee: TypedContractMethod<[], [bigint], "view">;

  claimCommission: TypedContractMethod<[], [void], "nonpayable">;

  createGame: TypedContractMethod<
    [_proof: BytesLike, _boardHash: BigNumberish, _betAmount: BigNumberish],
    [bigint],
    "payable"
  >;

  createVerifier: TypedContractMethod<[], [string], "view">;

  game: TypedContractMethod<
    [_gameID: BigNumberish],
    [Battleship.GamePublicMetadataStructOutput],
    "view"
  >;

  joinGame: TypedContractMethod<
    [_gameID: BigNumberish, _proof: BytesLike, _boardHash: BigNumberish],
    [void],
    "payable"
  >;

  moveVerifier: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  submitMove: TypedContractMethod<
    [
      _gameID: BigNumberish,
      _moveX: BigNumberish,
      _moveY: BigNumberish,
      _proof: BytesLike,
      isPreviousMoveAHit: boolean
    ],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "accumulatedFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "claimCommission"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createGame"
  ): TypedContractMethod<
    [_proof: BytesLike, _boardHash: BigNumberish, _betAmount: BigNumberish],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "createVerifier"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "game"
  ): TypedContractMethod<
    [_gameID: BigNumberish],
    [Battleship.GamePublicMetadataStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "joinGame"
  ): TypedContractMethod<
    [_gameID: BigNumberish, _proof: BytesLike, _boardHash: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "moveVerifier"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitMove"
  ): TypedContractMethod<
    [
      _gameID: BigNumberish,
      _moveX: BigNumberish,
      _moveY: BigNumberish,
      _proof: BytesLike,
      isPreviousMoveAHit: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
