/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as iProofVerificationSol from "./IProofVerification.sol";
export { IBunnyBattle__factory } from "./IBunnyBattle__factory";
